language: d
d: dmd

script:
    - dub build --compiler=${DC} --build=release
    - dub test --compiler=${DC} --build=unittest-cov --combined
    # see https://github.com/rejectedsoftware/vibe.d/issues/767 for --combined
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        - cromfr@gmail.com
